=begin
#Quick Base API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for QuickBase::ReportsQueryFormulaFields
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReportsQueryFormulaFields' do
  before do
    # run before each test
    @instance = QuickBase::ReportsQueryFormulaFields.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReportsQueryFormulaFields' do
    it 'should create an instance of ReportsQueryFormulaFields' do
      expect(@instance).to be_instance_of(QuickBase::ReportsQueryFormulaFields)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "label"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "field_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["rich-text", "text", "numeric", "currency", "percent", "rating", "date", "timestamp", "timeofday", "duration", "checkbox", "phone", "email", "user", "multiuser", "url"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.field_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "formula"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "decimal_precision"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
