=begin
#Quick Base API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

# Common files
require 'quick_base/api_client'
require 'quick_base/api_error'
require 'quick_base/version'
require 'quick_base/configuration'

# Models
require 'quick_base/models/apps_variables'
require 'quick_base/models/fields_permissions'
require 'quick_base/models/fields_properties'
require 'quick_base/models/fieldsfield_id_properties'
require 'quick_base/models/fieldsusage_field'
require 'quick_base/models/fieldsusage_usage'
require 'quick_base/models/fieldsusage_usage_actions'
require 'quick_base/models/fieldsusage_usage_app_home_pages'
require 'quick_base/models/fieldsusage_usage_default_reports'
require 'quick_base/models/fieldsusage_usage_exact_forms'
require 'quick_base/models/fieldsusage_usage_fields'
require 'quick_base/models/fieldsusage_usage_forms'
require 'quick_base/models/fieldsusage_usage_notifications'
require 'quick_base/models/fieldsusage_usage_personal_reports'
require 'quick_base/models/fieldsusage_usage_relationships'
require 'quick_base/models/fieldsusage_usage_reminders'
require 'quick_base/models/fieldsusage_usage_reports'
require 'quick_base/models/fieldsusage_usage_roles'
require 'quick_base/models/fieldsusage_usage_webhooks'
require 'quick_base/models/generated'
require 'quick_base/models/generated_1'
require 'quick_base/models/generated_10'
require 'quick_base/models/generated_11'
require 'quick_base/models/generated_12'
require 'quick_base/models/generated_2'
require 'quick_base/models/generated_3'
require 'quick_base/models/generated_4'
require 'quick_base/models/generated_5'
require 'quick_base/models/generated_6'
require 'quick_base/models/generated_7'
require 'quick_base/models/generated_8'
require 'quick_base/models/generated_9'
require 'quick_base/models/inline_response_200'
require 'quick_base/models/inline_response_200_1'
require 'quick_base/models/inline_response_200_2'
require 'quick_base/models/inline_response_200_3'
require 'quick_base/models/recordsquery_group_by'
require 'quick_base/models/recordsquery_options'
require 'quick_base/models/reports_query'
require 'quick_base/models/reports_query_formula_fields'
require 'quick_base/models/tablestable_idrelationship_foreign_key_field'
require 'quick_base/models/tablestable_idrelationship_summary_fields'

# APIs
require 'quick_base/api/apps_api'
require 'quick_base/api/auth_api'
require 'quick_base/api/fields_api'
require 'quick_base/api/files_api'
require 'quick_base/api/records_api'
require 'quick_base/api/reports_api'
require 'quick_base/api/tables_api'

module QuickBase
  class << self
    # Customize default settings for the SDK using block.
    #   QuickBase.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
